# Generated by Django 4.1.6 on 2023-07-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='encadreur',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='merged',
            field=models.BooleanField(default=False),
        ),
    ]
