# Generated by Django 4.1.6 on 2023-08-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_membre_encadreur_membre_merged'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nouveau',
        ),
    ]
