# Generated by Django 4.1.6 on 2023-09-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0003_delete_nouveau'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evenement',
        ),
    ]
