# Generated by Django 4.1.6 on 2023-07-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palier',
            name='libelle',
        ),
        migrations.AddField(
            model_name='palier',
            name='montant',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
