# Generated by Django 4.1.6 on 2023-09-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_palier_libelle_palier_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mission')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('membres', models.JSONField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mission')),
            ],
        ),
    ]
