# Generated by Django 4.1.6 on 2023-09-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_evenements_communicationliste'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunicationListe',
            new_name='Communication',
        ),
        migrations.RenameModel(
            old_name='Evenements',
            new_name='Evenement',
        ),
    ]
