# Generated by Django 4.1.6 on 2023-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_communicationliste_communication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='mission',
        ),
        migrations.AlterField(
            model_name='communication',
            name='membres',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
