# Generated by Django 4.1.6 on 2023-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='membre',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
