# Generated by Django 4.1.6 on 2023-09-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_timeline_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='membre',
            field=models.IntegerField(),
        ),
    ]
