# Generated by Django 4.1.6 on 2023-09-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_communication_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='mission',
        ),
    ]
