# Generated by Django 4.1.6 on 2023-09-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreecaisse',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
    ]
