# Generated by Django 4.1.6 on 2023-09-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_entreecaisse_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortiecaisse',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='suivibanque',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
    ]
