# Generated by Django 4.1.6 on 2023-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_sortiecaisse_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortiecaisse',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to='sorties/'),
        ),
    ]
