# Generated by Django 4.1.6 on 2024-01-12 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_communication_mission'),
        ('finances', '0004_sortiecaisse_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivibanque',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.mission'),
        ),
    ]
