# Generated by Django 4.1.6 on 2023-08-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0003_delete_nouveau'),
        ('common', '0002_remove_palier_libelle_palier_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.DateField()),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mission')),
                ('palier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.palier')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('sens', models.CharField(max_length=3)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagements.engagement')),
            ],
        ),
    ]
