# Generated by Django 4.1.6 on 2023-08-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_depenses_remove_mouvement_sens_mouvement_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depenses',
            new_name='Depense',
        ),
    ]
