# Generated by Django 4.1.6 on 2023-08-03 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0003_delete_nouveau'),
        ('common', '0002_remove_palier_libelle_palier_montant'),
        ('engagements', '0003_rename_depenses_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='engagement',
            unique_together={('mission', 'membre', 'palier', 'annee')},
        ),
    ]
