# Generated by Django 4.1.6 on 2023-09-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_communication_mission'),
        ('engagements', '0005_depense_date_depense_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='mission',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='common.mission'),
            preserve_default=False,
        ),
    ]
