# Generated by Django 4.1.6 on 2023-09-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0006_depense_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='mission',
        ),
    ]
