# Generated by Django 4.1.6 on 2023-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0007_remove_depense_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to='depenses/'),
        ),
    ]
